-- CONEXIÓN BASE DE DATOS "SIRA" A ESQUEMA "ACADEMICO" PARA LA APP WEB DE "INVITADOS GRADOS"

-- TABLA GI_CEREMONIAS_TB 
CREATE TABLE
    "ACADEMICO"."GI_CEREMONIAS_TB" (
        "ID_CEREMONIA" NUMBER(*, 0) NOT NULL ENABLE,
        "FECHA" DATE,
        "HORA" VARCHAR2(50 BYTE),
        "NOMBRE" VARCHAR2(80 BYTE),
        "DESCRIPCION" VARCHAR2(250 BYTE),
        "ESTADO" VARCHAR2(100 BYTE),
        "CANT_INV" VARCHAR2(10 BYTE),
        "CICLO" VARCHAR2(100 BYTE),
        PRIMARY KEY ("ID_CEREMONIA") ENABLE
    ) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
        INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    ) TABLESPACE "ACADEMICO";

-- TABLA GI_GRADUANDOS_TB (USUARIOS)
CREATE TABLE
    "ACADEMICO"."GI_GRADUANDOS_TB" (
        "DOCUMENTO_GRADUANDO" NUMBER(10, 0) NOT NULL ENABLE,
        "TIPO_IDENTIFICACION" VARCHAR2(100 BYTE) NOT NULL ENABLE,
        "NOMBRES" VARCHAR2(100 BYTE) NOT NULL ENABLE,
        "APELLIDOS" VARCHAR2(100 BYTE) NOT NULL ENABLE,
        "CLAVE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
        "PERFIL" VARCHAR2(45 BYTE) NOT NULL ENABLE,
        "CORREO_PERSONAL" VARCHAR2(100 BYTE),
        "CORREO_INSTITUCIONAL" VARCHAR2(100 BYTE),
        "TELEFONO" VARCHAR2(50 BYTE),
        "CICLO" VARCHAR2(100 BYTE),
        CONSTRAINT "PK_GRADUANDOS" PRIMARY KEY ("DOCUMENTO_GRADUANDO") ENABLE
    ) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
        INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    ) TABLESPACE "ACADEMICO";

-- TABLA GI_RELACION_TB
CREATE TABLE
    "ACADEMICO"."GI_RELACION_TB" (
        "ID_RELACION" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE MAXVALUE INCREMENT BY START
        WITH
            1 CACHE NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE,
            "DOCUMENTO_GRADUANDO" NUMBER(10, 0) NOT NULL ENABLE,
            "ID_CEREMONIA" NUMBER(20, 0),
            "ID_VPLANES" VARCHAR2(50 BYTE),
            "CANT_INV" VARCHAR2(10 BYTE),
            "ESTADO" VARCHAR2(100 BYTE),
            CONSTRAINT "GI_RELACION_TB_PK" PRIMARY KEY ("ID_RELACION") ENABLE,
            CONSTRAINT "UNI_RELACION" UNIQUE (
                "DOCUMENTO_GRADUANDO",
                "ID_CEREMONIA",
                "ID_VPLANES"
            ) ENABLE,
            CONSTRAINT "FK_RELACION_GRADUANDOS" FOREIGN KEY ("DOCUMENTO_GRADUANDO") REFERENCES "ACADEMICO"."GI_GRADUANDOS_TB" ("DOCUMENTO_GRADUANDO") ENABLE,
            CONSTRAINT "FK_RELACION_CEREMONIA" FOREIGN KEY ("ID_CEREMONIA") REFERENCES "ACADEMICO"."GI_CEREMONIAS_TB" ("ID_CEREMONIA") ENABLE
    ) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
        INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    ) TABLESPACE "ACADEMICO";

-- TABLA GI_INVITADOS_TB
CREATE TABLE
    "ACADEMICO"."GI_INVITADOS_TB" (
        "ID_REGISTRO" NUMBER(10, 0) GENERATED ALWAYS AS IDENTITY MINVALUE MAXVALUE INCREMENT BY START
        WITH
            1 CACHE NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE,
            "DOCUMENTO_INV" NUMBER(20, 0) NOT NULL ENABLE,
            "TIPO_IDENTIFICACION" VARCHAR2(45 BYTE),
            "NOMBRES" VARCHAR2(100 BYTE),
            "APELLIDOS" VARCHAR2(100 BYTE),
            "CORREO" VARCHAR2(100 BYTE),
            "ID_RELACION" NUMBER(10, 0) NOT NULL ENABLE,
            CONSTRAINT "PK_INVITADOS" PRIMARY KEY ("ID_REGISTRO") ENABLE,
            CONSTRAINT "GI_INVITADOS_TB_FK1" FOREIGN KEY ("ID_RELACION") REFERENCES "ACADEMICO"."GI_RELACION_TB" ("ID_RELACION") ENABLE
    ) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
        INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    ) TABLESPACE "ACADEMICO";

-- TABLA GI_INVITACIONES_TB
CREATE TABLE
    "ACADEMICO"."GI_INVITACIONES_TB" (
        "ID_INVITACIONES" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE MAXVALUE INCREMENT BY START
        WITH
            1 CACHE NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE,
            "ID_REGISTRO" NUMBER(10, 0) NOT NULL ENABLE,
            "ESTADO" VARCHAR2(100 BYTE) NOT NULL ENABLE,
            "FECHA" TIMESTAMP (6),
            "EPOCH" VARCHAR2(200 BYTE),
            CONSTRAINT "PK_INVITACIONES" PRIMARY KEY ("ID_INVITACIONES") ENABLE,
            CONSTRAINT "FK_INVITACIONES_INVITADOS" FOREIGN KEY ("ID_REGISTRO") REFERENCES "ACADEMICO"."GI_INVITADOS_TB" ("ID_REGISTRO") DISABLE
    ) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
        INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    ) TABLESPACE "ACADEMICO";



GRANT
    ALTER ON "ACADEMICO"."GI_INVITADOS_TB" TO "DMCARDENASH"
WITH
GRANT OPTION;

GRANT
DELETE
    ON "ACADEMICO"."GI_INVITADOS_TB" TO "DMCARDENASH"
WITH
GRANT OPTION;

GRANT
INSERT
    ON "ACADEMICO"."GI_INVITADOS_TB" TO "DMCARDENASH"
WITH
GRANT OPTION;

GRANT
SELECT
    ON "ACADEMICO"."GI_INVITADOS_TB" TO "DMCARDENASH"
WITH
GRANT OPTION;

GRANT
UPDATE
    ON "ACADEMICO"."GI_INVITADOS_TB" TO "DMCARDENASH"
WITH
GRANT OPTION;